name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cp src/environments/environment.example.ts src/environments/environment.ts
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TECNO_AIR_COLD }}
          channelId: live
          projectId: tecno-air-cold
          target: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
